name: Build
on:
  push:
    tags:
      - v**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    # strategy:  
    #    matrix:  
    #      configuration: [BETA]
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get branch names
      id: branch-names
      uses: tj-actions/branch-names@v8
      with:
        strip_tag_prefix: v # Optionally strip the leading `v` from the tag.

    - name: Get short SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    # - name: Set Describe
    #   shell: bash
    #   run: |
    #       describe=`git describe --tags --always`
    #       echo "describe=$describe" >> $GITHUB_ENV

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    # - name: Replace
    #   run: |
    #     (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const OAuthClientId As String = ""', 'Public Const OAuthClientId As String = "${{ secrets.CLIENT_ID }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
    #     (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const CurseForgeAPIKey As String = ""', 'Public Const CurseForgeAPIKey As String = "${{ secrets.CURSEFORGE_API_KEY }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
    #     (gc "Plain Craft Launcher 2\Modules\Base\ModBase.vb") -replace 'Public Const CommitHash As String = ""', 'Public Const CommitHash As String = "${{ github.sha }}"' | Out-File "Plain Craft Launcher 2\Modules\Base\ModBase.vb"
    #     rm "Plain Craft Launcher 2\Resources\Help.zip"
    #     aria2c "--out=Plain Craft Launcher 2\Resources\Help.zip" "https://codeload.github.com/LTCatt/PCL2Help/zip/refs/heads/master"
    #     7z x "Plain Craft Launcher 2\Resources\Help.zip" -o"Plain Craft Launcher 2\Resources"
    #     rm "Plain Craft Launcher 2\Resources\Help.zip"
    #     rm "Plain Craft Launcher 2\Resources\PCL2Help-master\*.*"
    #     7z a "Plain Craft Launcher 2\Resources\Help.zip" ".\Plain Craft Launcher 2\Resources\PCL2Help-master\*"
    #     rm "Plain Craft Launcher 2\Resources\PCL2Help-master\" -Recurse

    - name: Build
      run: msbuild "Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj" -p:Configuration=BETA
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      if: steps.branch-names.outputs.is_tag == 'true'
      with:
        name: ${{ steps.branch-names.outputs.tag }}
        path: Plain Craft Launcher 2\obj\BETA\Plain Craft Launcher 2.exe

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      if: steps.branch-names.outputs.is_tag == 'false'
      with:
        name: ${{ steps.branch-names.outputs.ref_branch }}-${{ steps.short-sha.outputs.sha }} 
        path: Plain Craft Launcher 2\obj\BETA\Plain Craft Launcher 2.exe
