name: Build
on:
  push:
    tags:
      - v**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    # strategy:  
    #    matrix:  
    #      configuration: [Debug, Release]

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get branch names
      id: branch-names
      uses: tj-actions/branch-names@v8
      with:
        strip_tag_prefix: v # Optionally strip the leading `v` from the tag.

    - name: Get short SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    # - name: Set Describe
    #   shell: bash
    #   run: |
    #       describe=`git describe --tags --always`
    #       echo "describe=$describe" >> $GITHUB_ENV

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    
    # - name: Update Help
    #   run:  |
    #     $workpath = [System.Environment]::CurrentDirectory
    #     Set-Location ..
    #     git clone https://github.com/LTCatt/PCL2Help.git -b master --single-branch --depth 1
    #     Set-Location PCL2Help
    #     Remove-Item -Path *.* -Recurse -Force
    #     Compress-Archive -Path .\* -DestinationPath .\Help.zip
    #     Copy-Item -Path .\Help.zip -Destination "${{ GITHUB.WORKSPACE }}\Plain Craft Launcher 2\Resources\Help.zip" -Force
    #     Set-Location ..
    #     Remove-Item PCL2Help -Recurse -Force
    #     Set-Location ${{ GITHUB.WORKSPACE }}


    # - name: Replace
    #   run: |
    #     (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const OAuthClientId As String = ""', 'Public Const OAuthClientId As String = "${{ secrets.CLIENT_ID }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
    #     (gc "Plain Craft Launcher 2\Modules\ModSecret.vb") -replace 'Public Const CurseForgeAPIKey As String = ""', 'Public Const CurseForgeAPIKey As String = "${{ secrets.CURSEFORGE_API_KEY }}"' | Out-File "Plain Craft Launcher 2\Modules\ModSecret.vb"
    #     (gc "Plain Craft Launcher 2\Modules\Base\ModBase.vb") -replace 'Public Const CommitHash As String = ""', 'Public Const CommitHash As String = "${{ github.sha }}"' | Out-File "Plain Craft Launcher 2\Modules\Base\ModBase.vb"
        
    - name: Build
      run: msbuild "Plain Craft Launcher 2\Plain Craft Launcher 2.vbproj" -p:Configuration=BETA

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      if: steps.branch-names.outputs.is_tag == 'true'
      with:
        name: ${{ steps.branch-names.outputs.tag }}
        path: Plain Craft Launcher 2\obj\BETA\Plain Craft Launcher 2.exe

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      if: steps.branch-names.outputs.is_tag == 'false'
      with:
        name: ${{ steps.branch-names.outputs.ref_branch }}-${{ steps.short-sha.outputs.sha }} 
        path: Plain Craft Launcher 2\obj\BETA\Plain Craft Launcher 2.exe
